name: mpcore
description: The MPFlutter core libs.
publish_to: none
version: 0.0.1
author: /
homepage: /

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter: 
    git: https://github.com/mpflutter/flutter
  json_patch: ^2.1.0
  vm_service_lib: ^0.3.5
  watcher: ^0.9.7
  glob: ^1.1.3
  mime_type: ^0.3.2
  path: ^1.8.0

dependency_overrides:
  flutter: 
    git: https://github.com/mpflutter/flutter